CC=g++                # Select Compiler (gcc)
CFLAGS=-I             # 
CFLAGS+=-Wall      
FILES=lab4.cpp        # File names to be compiled

Lab4Test: $(FILES)       
	$(CC) $(CFLAGS) $(FILES) -o Lab4


clean:
	rm -f lab4

all: Lab4Test
